name: CICD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: Login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build docker image
        run: docker build -t aishwaryak15/winepark-terraform .
      - name: Publish image to docker hub
        run: docker push aishwaryak15/winepark-terraform:latest

  deploy:
    needs: build
    runs-on: [aws-ec]
    steps:
      - name: Pull Image from docker hub
        run: sudo docker pull aishwaryak15/winepark-terraform:latest
      - name: Delete old container
        run: sudo docker rm -f winepark-terraform-container
      - name: Run docker container
        run: sudo docker run -d -p 8080:8080 --name winepark-terraform-container aishwaryak15/winepark-terraform
